export const CAR_MAKES = [
  "Abarth", "Acura", "Alfa Romeo", "Aston Martin", "Audi",
  "Bentley", "BMW", "Bugatti", "BYD",
  "Cadillac", "Chery", "Chevrolet", "Chrysler", "Citroën", "Cupra",
  "Dacia", "Dodge", "DS",
  "Ferrari", "Fiat", "Ford",
  "Geely", "Genesis", "GWM",
  "Haval", "Honda", "Hyundai",
  "Infiniti",
  "Jaecoo", "Jaguar", "Jeep",
  "Kia",
  "Lamborghini", "Lancia", "Land Rover", "Leapmotor", "Lexus", "Li Auto", "Lincoln", "Lynk & Co",
  "Mahindra", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "MG", "Mini", "Mitsubishi",
  "NIO", "Nissan",
  "OMODA", "Opel",
  "Peugeot", "Porsche",
  "RAM", "Renault", "Rolls-Royce",
  "SEAT", "Skoda", "Smart", "Subaru", "Suzuki",
  "Tata", "Tesla", "Toyota",
  "Volkswagen", "Volvo",
  "Xpeng",
  "Zeekr",
]

export const CAR_MODELS_BY_MAKE: Record<string, string[]> = {
  "Abarth": ["124 Spider", "500", "595", "695"],
  "Acura": ["ILX", "Integra", "MDX", "RDX", "TLX", "ZDX"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale", "Junior", "147", "156", "159"],
  "Aston Martin": ["DB11", "DB12", "DBS", "DBX", "Vantage", "Valkyrie"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q6 e-tron", "Q7", "Q8", "TT", "e-tron GT", "RS3", "RS6", "S3", "S5"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulliner"],
  "BMW": ["Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "Serie 7", "X1", "X2", "X3", "X5", "X6", "X7", "i3", "i4", "i5", "i7", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5", "Z4"],
  "Bugatti": ["Chiron", "Divo", "Mistral", "Tourbillon", "Veyron"],
  "BYD": ["Atto 3", "Dolphin", "Han", "Hawk", "Seal", "Seagull", "Sealion 6", "Sealion 7", "Shark", "Song Plus", "Tang", "Yuan Plus"],
  "Cadillac": ["CT4", "CT5", "Escalade", "Lyriq", "XT4", "XT5", "XT6"],
  "Chery": ["Arrizo 5", "Arrizo 6", "Omoda 5", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  "Chevrolet": ["Blazer", "Bolt EV", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado", "Suburban", "Tahoe", "Trailblazer", "Traverse"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroën": ["Berlingo", "C1", "C3", "C3 Aircross", "C4", "C5 Aircross", "C5 X", "C-Elysée", "ë-C3", "ë-C4", "ë-Berlingo"],
  "Cupra": ["Ateca", "Born", "Formentor", "Leon", "Tavascan", "Terramar"],
  "Dacia": ["Bigster", "Duster", "Jogger", "Logan", "Sandero", "Spring"],
  "Dodge": ["Challenger", "Charger", "Durango", "Hornet"],
  "DS": ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Ferrari": ["296 GTB", "296 GTS", "812 Superfast", "F8 Tributo", "Portofino", "Purosangue", "Roma", "SF90 Stradale"],
  "Fiat": ["500", "500e", "500L", "500X", "Bravo", "Doblo", "Fastback", "Grande Panda", "Panda", "Punto", "Tipo"],
  "Ford": ["Bronco", "EcoSport", "Edge", "Explorer", "F-150", "Focus", "Kuga", "Mondeo", "Mustang", "Mustang Mach-E", "Puma", "Ranger", "Transit Custom"],
  "Geely": ["Atlas Pro", "Coolray", "Emgrand", "Galaxy L7", "Monjaro", "Tugella"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GWM": ["Ora 03", "Poer", "Wey Coffee 01", "Wey Coffee 02"],
  "Haval": ["Dargo", "H6", "Jolion", "XEV7"],
  "Honda": ["Accord", "Civic", "CR-V", "e", "e:Ny1", "HR-V", "Jazz", "ZR-V"],
  "Hyundai": ["i10", "i20", "i30", "IONIQ 5", "IONIQ 6", "IONIQ 9", "Kona", "Santa Fe", "Tucson"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  "Jaecoo": ["J5", "J6", "J7", "J8"],
  "Jaguar": ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "XE", "XF"],
  "Jeep": ["Avenger", "Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  "Kia": ["Ceed", "EV3", "EV6", "EV9", "Niro", "Picanto", "ProCeed", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "XCeed"],
  "Lamborghini": ["Huracan", "Revuelto", "Urus"],
  "Lancia": ["Delta", "Stratos", "Ypsilon"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Leapmotor": ["C10", "T03"],
  "Lexus": ["CT", "ES", "GS", "IS", "LC", "LX", "NX", "RX", "RZ", "TX", "UX"],
  "Li Auto": ["L6", "L7", "L8", "L9", "MEGA"],
  "Lincoln": ["Aviator", "Corsair", "Navigator", "Nautilus"],
  "Lynk & Co": ["01", "02", "03", "05", "06", "09"],
  "Mahindra": ["Scorpio", "Thar", "XUV300", "XUV400", "XUV700"],
  "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-5", "MX-30"],
  "McLaren": ["570S", "600LT", "720S", "750S", "Artura", "GT"],
  "Mercedes-Benz": ["AMG GT", "Clase A", "Clase B", "Clase C", "Clase E", "Clase G", "Clase S", "CLA", "CLE", "EQA", "EQB", "EQC", "EQE", "EQS", "GLA", "GLB", "GLC", "GLE", "GLS", "SL", "Sprinter"],
  "MG": ["3", "4", "5", "Cyberster", "HS", "Marvel R", "MG7", "ZS"],
  "Mini": ["3 Puertas", "5 Puertas", "Aceman", "Clubman", "Convertible", "Countryman", "Electric", "Paceman"],
  "Mitsubishi": ["ASX", "Eclipse Cross", "L200", "Outlander", "Space Star"],
  "NIO": ["EC6", "EL6", "ES6", "ES8", "ET5", "ET7", "ETP9"],
  "Nissan": ["Ariya", "Juke", "Leaf", "Micra", "Navara", "Qashqai", "X-Trail", "Z"],
  "OMODA": ["5", "C5", "E5"],
  "Opel": ["Adam", "Astra", "Combo", "Corsa", "Crossland", "Frontera", "Grandland", "Insignia", "Mokka", "Zafira"],
  "Peugeot": ["108", "208", "308", "408", "508", "2008", "3008", "5008", "e-208", "e-2008", "e-3008", "e-5008"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  "RAM": ["1500", "2500", "3500", "ProMaster"],
  "Renault": ["Arkana", "Austral", "Captur", "Clio", "Espace", "Kadjar", "Kangoo", "Megane", "R5 E-Tech", "Scenic", "Symbioz", "Twingo", "Zoe"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre", "Wraith"],
  "SEAT": ["Arona", "Arosa", "Ateca", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"],
  "Skoda": ["Elroq", "Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Scala", "Superb"],
  "Smart": ["#1", "#3", "EQ forfour", "EQ fortwo"],
  "Subaru": ["BRZ", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "XV / Crosstrek"],
  "Suzuki": ["Baleno", "Fronx", "Ignis", "Jimny", "S-Cross", "Swift", "Vitara"],
  "Tata": ["Harrier", "Nexon", "Punch", "Safari", "Tiago"],
  "Tesla": ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  "Toyota": ["Aygo X", "BZ4X", "C-HR", "Camry", "Corolla", "GR Yaris", "GR86", "Hilux", "Land Cruiser", "Prius", "Proace City", "RAV4", "Yaris", "Yaris Cross"],
  "Volkswagen": ["Arteon", "Golf", "ID.3", "ID.4", "ID.5", "ID.7", "Polo", "Sharan", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Up!"],
  "Volvo": ["C40 Recharge", "EX30", "EX40", "EX90", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  "Xpeng": ["G6", "G9", "P5", "P7", "X9"],
  "Zeekr": ["001", "007", "009", "X"],
}

export function getModelsForMake(make: string): string[] {
  return CAR_MODELS_BY_MAKE[make] ?? []
}
